requires 'perl', '5.036';

on build => sub {
  requires 'Email::Valid';
  requires 'Data::Monad::Either';
  requires 'String::Util';
  requires 'Number::Phone';
  requires 'Data::UUID';
  requires 'Crypt::PBKDF2';
  requires 'JSON::WebToken';
  requires 'Try::Tiny';
  requires 'ExtUtils::MakeMaker';
};

on test => sub {
  requires 'Test::More';
  requires 'Data::Dump';
  requires 'lib::relative';
};
