requires 'perl', '5.036';

on build => sub {
  requires 'Mojo::JSON';
  requires 'Net::AMQP::RabbitMQ';
  requires 'Data::Monad::Either';
  requires 'ExtUtils::MakeMaker';
};

on test => sub {
  requires 'Dotenv';
  requires 'Test::More';
  requires 'Data::Dump';
  requires 'lib::relative';
};